# Generated by Django 3.1.7 on 2021-03-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_female', models.BooleanField(default=False)),
                ('dob', models.TextField()),
                ('enrollment', models.TextField(default='undefined')),
                ('uid', models.TextField(default='GUR/00000/12')),
                ('term', models.TextField(default='undefined')),
                ('contact', models.TextField(default='undefined')),
                ('access', models.TextField(default='undefined')),
            ],
        ),
    ]
